# P4P-only parameter variations (pay4partner = true only)
# Used for increasing n on the main paper results

# -------------------------
# pay4partner = true, no contract
# -------------------------
- with_message_history: false
  pay4partner: true
  contract_type: null
  fog_of_war: [false, false]
  selfish: [true, true]

# -------------------------
# pay4partner = true, strict (Prog-Trading)
# -------------------------
- with_message_history: false
  pay4partner: true
  contract_type: strict
  fog_of_war: [false, false]
  selfish: [true, true]

# -------------------------
# pay4partner = true, contract_for_finishing (Prog-Points)
# -------------------------
- with_message_history: false
  pay4partner: true
  contract_type: contract_for_finishing
  fog_of_war: [false, false]
  selfish: [true, true]

# -------------------------
# pay4partner = true, tile_with_judge_implementation (NL-Trading)
# -------------------------
- with_message_history: false
  pay4partner: true
  contract_type: tile_with_judge_implementation
  fog_of_war: [false, false]
  selfish: [true, true]
