# Remaining configs needed to reach n=5 (No Contract already done)

- with_message_history: false
  pay4partner: true
  contract_type: contract_for_finishing
  fog_of_war: [false, false]
  selfish: [true, true]

- with_message_history: false
  pay4partner: true
  contract_type: tile_with_judge_implementation
  fog_of_war: [false, false]
  selfish: [true, true]

- with_message_history: false
  pay4partner: true
  contract_type: strict
  fog_of_war: [false, false]
  selfish: [true, true]
