# Prog-Trading only (p4p=true, strict contract)
# Used for re-running broken Prog-Trading logs after player name fix

- with_message_history: false
  pay4partner: true
  contract_type: strict
  fog_of_war: [false, false]
  selfish: [true, true]
