grid_size: 5
colors:
  - R
  - B
  - G
resource_mode: manual
grid:
  - [G, R, R, R, R]
  - [R, R, B, R, R]
  - [B, B, R, B, R]
  - [B, R, R, R, R]
  - [B, B, B, B, G]
manual_resources:
  - G: 20
    B: 20
  - G: 20
    R: 20
manual_start_positions:
  - [2, 2]
  - [0, 0]
