grid_size: 5
colors:
  - R
  - B
  - G
  - PK
  - Y
resource_mode: manual
grid:
  - ["G", "R", "R", "R", "R"]
  - ["B", "PK", "PK", "PK", "R"]
  - ["B", "PK", "G", "G", "G"]
  - ["B", "PK", "G", "Y", "B"]
  - ["B", "B", "G", "R", "G"]
manual_resources:
  - G: 20
    B: 20
  - G: 20
    R: 20
