grid_size: 5
colors:
  - R
  - B
  - G
  - Y
resource_mode: manual
grid:
  - [G, B, R, B, R]
  - [R, Y, B, R, B]
  - [B, R, Y, B, R]
  - [R, B, R, Y, B]
  - [B, R, B, R, G]
manual_resources:
  - R: 20
    G: 4
  - B: 20
    G: 4
