grid_size: 5
colors:
  - R
  - B
  - G
  - Y
resource_mode: manual
grid:
  - [G, Y, Y, Y, G]
  - [G, Y, Y, Y, G]
  - [G, Y, Y, Y, G]
  - [G, R, G, B, G]
  - [G, B, G, R, G]
manual_resources:
  - G: 20
    B: 4
  - G: 20
    R: 4
manual_start_positions:
  - [0, 0]
  - [0, 4]
manual_goal_positions:
  - [4, 4]
  - [4, 0]
