grid_size: 6
colors:
  - R
  - B
  - G

resource_mode: manual

grid:
  - [G, B, B, R, R, R]
  - [B, B, B, R, R, R]
  - [R, B, R, R, R, R]
  - [R, B, R, B, B, B]
  - [B, B, B, B, R, B]
  - [R, B, R, R, B, G]

manual_resources:
  - G: 1
    B: 14
  - G: 1
    R: 14
