grid_size: 5
colors:
  - R
  - B
  - G
  - Y
  - PK
resource_mode: manual
grid:
  - [G, G, G, G, B]
  - [G, Y, Y, Y, R]
  - [G, PK, G, G, G]
  - [G, Y, G, Y, G]
  - [G, G, G, Y, G]
manual_resources:
  - G: 20
    B: 20
  - G: 20
    R: 20
