grid_size: 7
colors:
  - R
  - B
  - G
resource_mode: manual
grid:
  - [G, G, B, B, B, B, B]
  - [G, R, R, R, R, R, B]
  - [B, R, R, R, R, R, B]
  - [B, R, R, R, B, B, R]
  - [B, R, R, B, B, B, B]
  - [B, R, R, B, R, R, B]
  - [B, B, B, B, R, R, G]
manual_resources:
  - R: 20
    G: 4
  - B: 20
    G: 4
